@extends('layouts.app')
@section('title','부서 관리')
@section('content')
<div class="panel"><div class="panel-header"><h2>부서 추가</h2></div><div class="panel-body"><form method="post" action="{{ route('admin.departments.store') }}" class="row g-3">@csrf
<div class="col-md-3"><label for="new-name" class="form-label">부서명</label><input id="new-name" class="form-control" name="name" required></div><div class="col-md-2"><label for="new-code" class="form-label">부서 코드</label><input id="new-code" class="form-control" name="code" required></div><div class="col-md-5"><label for="new-desc" class="form-label">설명</label><input id="new-desc" class="form-control" name="description"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">부서 추가</button></div></form></div></div>
@forelse($departments as $department)<div class="panel"><div class="panel-body"><form class="row g-3" method="post" action="{{ route('admin.departments.update',$department) }}">@csrf @method('PUT')
<div class="col-md-3"><label class="form-label" for="name-{{ $department->id }}">부서명</label><input id="name-{{ $department->id }}" class="form-control" name="name" value="{{ $department->name }}" required></div><div class="col-md-2"><label class="form-label" for="code-{{ $department->id }}">부서 코드</label><input id="code-{{ $department->id }}" class="form-control" name="code" value="{{ $department->code }}" required></div><div class="col-md-5"><label class="form-label" for="desc-{{ $department->id }}">설명</label><input id="desc-{{ $department->id }}" class="form-control" name="description" value="{{ $department->description }}"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-light w-100">변경 저장</button></div></form>
<div class="d-flex justify-content-between align-items-center mt-3"><span class="subtle">사용자 {{ $department->users_count }}명 · 문서 {{ $department->documents_count }}개</span>@if(!$department->users_count && !$department->documents_count)<form method="post" action="{{ route('admin.departments.destroy',$department) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">빈 부서 삭제</button></form>@endif</div>
</div></div>@empty<div class="empty-state">첫 번째 부서를 등록하세요.</div>@endforelse
@endsection
